# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: D:/JARS2x/adi_minimal_reduced_125MHz_sgmii/hdl/projects/fmcjesdadc1/kc705/system_constr.xdc

# XDC: D:/JARS2x/adi_minimal_reduced_125MHz_sgmii/hdl/projects/common/kc705/kc705_system_constr.xdc

# Block Designs: bd/system/system.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system || ORIG_REF_NAME==system} -quiet] -quiet

# IP: bd/system/ip/system_sys_mb_0/system_sys_mb_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_sys_mb_0 || ORIG_REF_NAME==system_sys_mb_0} -quiet] -quiet

# IP: bd/system/ip/system_sys_dlmb_0/system_sys_dlmb_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_sys_dlmb_0 || ORIG_REF_NAME==system_sys_dlmb_0} -quiet] -quiet

# IP: bd/system/ip/system_sys_ilmb_0/system_sys_ilmb_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_sys_ilmb_0 || ORIG_REF_NAME==system_sys_ilmb_0} -quiet] -quiet

# IP: bd/system/ip/system_sys_dlmb_cntlr_0/system_sys_dlmb_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_sys_dlmb_cntlr_0 || ORIG_REF_NAME==system_sys_dlmb_cntlr_0} -quiet] -quiet

# IP: bd/system/ip/system_sys_ilmb_cntlr_0/system_sys_ilmb_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_sys_ilmb_cntlr_0 || ORIG_REF_NAME==system_sys_ilmb_cntlr_0} -quiet] -quiet

# IP: bd/system/ip/system_sys_lmb_bram_0/system_sys_lmb_bram_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_sys_lmb_bram_0 || ORIG_REF_NAME==system_sys_lmb_bram_0} -quiet] -quiet

# IP: bd/system/ip/system_sys_mb_debug_0/system_sys_mb_debug_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_sys_mb_debug_0 || ORIG_REF_NAME==system_sys_mb_debug_0} -quiet] -quiet

# IP: bd/system/ip/system_sys_rstgen_0/system_sys_rstgen_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_sys_rstgen_0 || ORIG_REF_NAME==system_sys_rstgen_0} -quiet] -quiet

# IP: bd/system/ip/system_sys_200m_rstgen_0/system_sys_200m_rstgen_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_sys_200m_rstgen_0 || ORIG_REF_NAME==system_sys_200m_rstgen_0} -quiet] -quiet

# IP: bd/system/ip/system_axi_ddr_cntrl_0/system_axi_ddr_cntrl_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_ddr_cntrl_0 || ORIG_REF_NAME==system_axi_ddr_cntrl_0} -quiet] -quiet

# IP: bd/system/ip/system_axi_uart_0/system_axi_uart_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_uart_0 || ORIG_REF_NAME==system_axi_uart_0} -quiet] -quiet

# IP: bd/system/ip/system_axi_spi_0/system_axi_spi_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_spi_0 || ORIG_REF_NAME==system_axi_spi_0} -quiet] -quiet

# IP: bd/system/ip/system_axi_gpio_0/system_axi_gpio_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_gpio_0 || ORIG_REF_NAME==system_axi_gpio_0} -quiet] -quiet

# IP: bd/system/ip/system_axi_intc_0/system_axi_intc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_intc_0 || ORIG_REF_NAME==system_axi_intc_0} -quiet] -quiet

# IP: bd/system/ip/system_sys_concat_intc_0/system_sys_concat_intc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_sys_concat_intc_0 || ORIG_REF_NAME==system_sys_concat_intc_0} -quiet] -quiet

# IP: bd/system/ip/system_axi_sysid_0_0/system_axi_sysid_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_sysid_0_0 || ORIG_REF_NAME==system_axi_sysid_0_0} -quiet] -quiet

# IP: bd/system/ip/system_rom_sys_0_0/system_rom_sys_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_rom_sys_0_0 || ORIG_REF_NAME==system_rom_sys_0_0} -quiet] -quiet

# IP: bd/system/ip/system_GND_1_0/system_GND_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_GND_1_0 || ORIG_REF_NAME==system_GND_1_0} -quiet] -quiet

# IP: bd/system/ip/system_xbar_0/system_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_xbar_0 || ORIG_REF_NAME==system_xbar_0} -quiet] -quiet

# IP: bd/system/ip/system_axi_cpu_interconnect_0/system_axi_cpu_interconnect_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_cpu_interconnect_0 || ORIG_REF_NAME==system_axi_cpu_interconnect_0} -quiet] -quiet

# IP: bd/system/ip/system_axi_mem_interconnect_0/system_axi_mem_interconnect_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_mem_interconnect_0 || ORIG_REF_NAME==system_axi_mem_interconnect_0} -quiet] -quiet

# Block Designs: bd/system/ip/system_axi_mem_interconnect_0/bd_0/bd_518a.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/system/ip/system_axi_mem_interconnect_0/bd_0/ip/ip_0/bd_518a_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/system/ip/system_axi_mem_interconnect_0/bd_0/ip/ip_1/bd_518a_psr0_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/system/ip/system_axi_mem_interconnect_0/bd_0/ip/ip_2/bd_518a_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/system/ip/system_axi_mem_interconnect_0/bd_0/ip/ip_3/bd_518a_psr_aclk1_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/system/ip/system_axi_mem_interconnect_0/bd_0/ip/ip_4/bd_518a_arsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/system/ip/system_axi_mem_interconnect_0/bd_0/ip/ip_5/bd_518a_rsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/system/ip/system_axi_mem_interconnect_0/bd_0/ip/ip_6/bd_518a_awsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/system/ip/system_axi_mem_interconnect_0/bd_0/ip/ip_7/bd_518a_wsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/system/ip/system_axi_mem_interconnect_0/bd_0/ip/ip_8/bd_518a_bsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/system/ip/system_axi_mem_interconnect_0/bd_0/ip/ip_9/bd_518a_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/system/ip/system_axi_mem_interconnect_0/bd_0/ip/ip_10/bd_518a_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/system/ip/system_axi_mem_interconnect_0/bd_0/ip/ip_11/bd_518a_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/system/ip/system_axi_mem_interconnect_0/bd_0/ip/ip_12/bd_518a_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/system/ip/system_axi_mem_interconnect_0/bd_0/ip/ip_13/bd_518a_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/system/ip/system_axi_mem_interconnect_0/bd_0/ip/ip_14/bd_518a_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/system/ip/system_axi_mem_interconnect_0/bd_0/ip/ip_15/bd_518a_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/system/ip/system_axi_mem_interconnect_0/bd_0/ip/ip_16/bd_518a_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/system/ip/system_axi_mem_interconnect_0/bd_0/ip/ip_17/bd_518a_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/system/ip/system_axi_mem_interconnect_0/bd_0/ip/ip_18/bd_518a_s01mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/system/ip/system_axi_mem_interconnect_0/bd_0/ip/ip_19/bd_518a_s01tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/system/ip/system_axi_mem_interconnect_0/bd_0/ip/ip_20/bd_518a_s01sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/system/ip/system_axi_mem_interconnect_0/bd_0/ip/ip_21/bd_518a_s01a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/system/ip/system_axi_mem_interconnect_0/bd_0/ip/ip_22/bd_518a_sarn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/system/ip/system_axi_mem_interconnect_0/bd_0/ip/ip_23/bd_518a_srn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/system/ip/system_axi_mem_interconnect_0/bd_0/ip/ip_24/bd_518a_s02mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/system/ip/system_axi_mem_interconnect_0/bd_0/ip/ip_25/bd_518a_s02tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/system/ip/system_axi_mem_interconnect_0/bd_0/ip/ip_26/bd_518a_s02sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/system/ip/system_axi_mem_interconnect_0/bd_0/ip/ip_27/bd_518a_s02a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/system/ip/system_axi_mem_interconnect_0/bd_0/ip/ip_28/bd_518a_sarn_2.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/system/ip/system_axi_mem_interconnect_0/bd_0/ip/ip_29/bd_518a_srn_2.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/system/ip/system_axi_mem_interconnect_0/bd_0/ip/ip_30/bd_518a_sawn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/system/ip/system_axi_mem_interconnect_0/bd_0/ip/ip_31/bd_518a_swn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/system/ip/system_axi_mem_interconnect_0/bd_0/ip/ip_32/bd_518a_sbn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/system/ip/system_axi_mem_interconnect_0/bd_0/ip/ip_33/bd_518a_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/system/ip/system_axi_mem_interconnect_0/bd_0/ip/ip_34/bd_518a_m00arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/system/ip/system_axi_mem_interconnect_0/bd_0/ip/ip_35/bd_518a_m00rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/system/ip/system_axi_mem_interconnect_0/bd_0/ip/ip_36/bd_518a_m00awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/system/ip/system_axi_mem_interconnect_0/bd_0/ip/ip_37/bd_518a_m00wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/system/ip/system_axi_mem_interconnect_0/bd_0/ip/ip_38/bd_518a_m00bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/system/ip/system_axi_mem_interconnect_0/bd_0/ip/ip_39/bd_518a_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/system/ip/system_GND_12_0/system_GND_12_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_GND_12_0 || ORIG_REF_NAME==system_GND_12_0} -quiet] -quiet

# IP: bd/system/ip/system_axi_ad9250_xcvr_0/system_axi_ad9250_xcvr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_ad9250_xcvr_0 || ORIG_REF_NAME==system_axi_ad9250_xcvr_0} -quiet] -quiet

# IP: bd/system/ip/system_rx_axi_0/system_rx_axi_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_rx_axi_0 || ORIG_REF_NAME==system_rx_axi_0} -quiet] -quiet

# IP: bd/system/ip/system_rx_0/system_rx_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_rx_0 || ORIG_REF_NAME==system_rx_0} -quiet] -quiet

# IP: bd/system/ip/system_axi_ad9250_core_0/system_axi_ad9250_core_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_ad9250_core_0 || ORIG_REF_NAME==system_axi_ad9250_core_0} -quiet] -quiet

# IP: bd/system/ip/system_util_fmcjesdadc1_xcvr_0/system_util_fmcjesdadc1_xcvr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_util_fmcjesdadc1_xcvr_0 || ORIG_REF_NAME==system_util_fmcjesdadc1_xcvr_0} -quiet] -quiet

# IP: bd/system/ip/system_ila_0_0/system_ila_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_ila_0_0 || ORIG_REF_NAME==system_ila_0_0} -quiet] -quiet

# XDC: bd/system/ip/system_sys_mb_0/system_sys_mb_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_sys_mb_0 || ORIG_REF_NAME==system_sys_mb_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/system/ip/system_sys_mb_0/system_sys_mb_0_ooc_debug.xdc

# XDC: bd/system/ip/system_sys_dlmb_0/system_sys_dlmb_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_sys_dlmb_0 || ORIG_REF_NAME==system_sys_dlmb_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/system/ip/system_sys_ilmb_0/system_sys_ilmb_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_sys_ilmb_0 || ORIG_REF_NAME==system_sys_ilmb_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/system/ip/system_sys_lmb_bram_0/system_sys_lmb_bram_0_ooc.xdc

# XDC: bd/system/ip/system_sys_mb_debug_0/system_sys_mb_debug_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_sys_mb_debug_0 || ORIG_REF_NAME==system_sys_mb_debug_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/system/ip/system_sys_mb_debug_0/system_sys_mb_debug_0_ooc_trace.xdc

# XDC: bd/system/ip/system_sys_rstgen_0/system_sys_rstgen_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_sys_rstgen_0 || ORIG_REF_NAME==system_sys_rstgen_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/system/ip/system_sys_rstgen_0/system_sys_rstgen_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_sys_rstgen_0 || ORIG_REF_NAME==system_sys_rstgen_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/system/ip/system_sys_200m_rstgen_0/system_sys_200m_rstgen_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_sys_200m_rstgen_0 || ORIG_REF_NAME==system_sys_200m_rstgen_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/system/ip/system_sys_200m_rstgen_0/system_sys_200m_rstgen_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_sys_200m_rstgen_0 || ORIG_REF_NAME==system_sys_200m_rstgen_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/system/ip/system_axi_ddr_cntrl_0/system_axi_ddr_cntrl_0/user_design/constraints/system_axi_ddr_cntrl_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_ddr_cntrl_0 || ORIG_REF_NAME==system_axi_ddr_cntrl_0} -quiet] -quiet

# XDC: bd/system/ip/system_axi_ddr_cntrl_0/system_axi_ddr_cntrl_0/user_design/constraints/system_axi_ddr_cntrl_0_ooc.xdc

# XDC: bd/system/ip/system_axi_ddr_cntrl_0/system_axi_ddr_cntrl_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_ddr_cntrl_0 || ORIG_REF_NAME==system_axi_ddr_cntrl_0} -quiet] -quiet

# XDC: bd/system/ip/system_axi_uart_0/system_axi_uart_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_axi_uart_0 || ORIG_REF_NAME==system_axi_uart_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/system/ip/system_axi_uart_0/system_axi_uart_0_ooc.xdc

# XDC: bd/system/ip/system_axi_uart_0/system_axi_uart_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_axi_uart_0 || ORIG_REF_NAME==system_axi_uart_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/system/ip/system_axi_spi_0/system_axi_spi_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_axi_spi_0 || ORIG_REF_NAME==system_axi_spi_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/system/ip/system_axi_spi_0/system_axi_spi_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_axi_spi_0 || ORIG_REF_NAME==system_axi_spi_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/system/ip/system_axi_spi_0/system_axi_spi_0_ooc.xdc

# XDC: bd/system/ip/system_axi_spi_0/system_axi_spi_0_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_axi_spi_0 || ORIG_REF_NAME==system_axi_spi_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/system/ip/system_axi_gpio_0/system_axi_gpio_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_axi_gpio_0 || ORIG_REF_NAME==system_axi_gpio_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/system/ip/system_axi_gpio_0/system_axi_gpio_0_ooc.xdc

# XDC: bd/system/ip/system_axi_gpio_0/system_axi_gpio_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_axi_gpio_0 || ORIG_REF_NAME==system_axi_gpio_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/system/ip/system_axi_intc_0/system_axi_intc_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_axi_intc_0 || ORIG_REF_NAME==system_axi_intc_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/system/ip/system_axi_intc_0/system_axi_intc_0_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_axi_intc_0 || ORIG_REF_NAME==system_axi_intc_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/system/ip/system_axi_intc_0/system_axi_intc_0_ooc.xdc

# XDC: bd/system/ip/system_axi_mem_interconnect_0/ooc.xdc

# XDC: bd/system/ip/system_axi_mem_interconnect_0/bd_0/ip/ip_1/bd_518a_psr0_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: bd/system/ip/system_axi_mem_interconnect_0/bd_0/ip/ip_1/bd_518a_psr0_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: bd/system/ip/system_axi_mem_interconnect_0/bd_0/ip/ip_2/bd_518a_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: bd/system/ip/system_axi_mem_interconnect_0/bd_0/ip/ip_2/bd_518a_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: bd/system/ip/system_axi_mem_interconnect_0/bd_0/ip/ip_3/bd_518a_psr_aclk1_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: bd/system/ip/system_axi_mem_interconnect_0/bd_0/ip/ip_3/bd_518a_psr_aclk1_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: bd/system/ip/system_axi_mem_interconnect_0/bd_0/ip/ip_4/bd_518a_arsw_0_ooc.xdc

# XDC: bd/system/ip/system_axi_mem_interconnect_0/bd_0/ip/ip_5/bd_518a_rsw_0_ooc.xdc

# XDC: bd/system/ip/system_axi_mem_interconnect_0/bd_0/ip/ip_6/bd_518a_awsw_0_ooc.xdc

# XDC: bd/system/ip/system_axi_mem_interconnect_0/bd_0/ip/ip_7/bd_518a_wsw_0_ooc.xdc

# XDC: bd/system/ip/system_axi_mem_interconnect_0/bd_0/ip/ip_8/bd_518a_bsw_0_ooc.xdc

# XDC: bd/system/ip/system_axi_mem_interconnect_0/bd_0/ip/ip_12/bd_518a_s00a2s_0_ooc.xdc

# XDC: bd/system/ip/system_axi_mem_interconnect_0/bd_0/ip/ip_13/bd_518a_sarn_0_ooc.xdc

# XDC: bd/system/ip/system_axi_mem_interconnect_0/bd_0/ip/ip_14/bd_518a_srn_0_ooc.xdc

# XDC: bd/system/ip/system_axi_mem_interconnect_0/bd_0/ip/ip_15/bd_518a_sawn_0_ooc.xdc

# XDC: bd/system/ip/system_axi_mem_interconnect_0/bd_0/ip/ip_16/bd_518a_swn_0_ooc.xdc

# XDC: bd/system/ip/system_axi_mem_interconnect_0/bd_0/ip/ip_17/bd_518a_sbn_0_ooc.xdc

# XDC: bd/system/ip/system_axi_mem_interconnect_0/bd_0/ip/ip_21/bd_518a_s01a2s_0_ooc.xdc

# XDC: bd/system/ip/system_axi_mem_interconnect_0/bd_0/ip/ip_22/bd_518a_sarn_1_ooc.xdc

# XDC: bd/system/ip/system_axi_mem_interconnect_0/bd_0/ip/ip_23/bd_518a_srn_1_ooc.xdc

# XDC: bd/system/ip/system_axi_mem_interconnect_0/bd_0/ip/ip_27/bd_518a_s02a2s_0_ooc.xdc

# XDC: bd/system/ip/system_axi_mem_interconnect_0/bd_0/ip/ip_28/bd_518a_sarn_2_ooc.xdc

# XDC: bd/system/ip/system_axi_mem_interconnect_0/bd_0/ip/ip_29/bd_518a_srn_2_ooc.xdc

# XDC: bd/system/ip/system_axi_mem_interconnect_0/bd_0/ip/ip_30/bd_518a_sawn_1_ooc.xdc

# XDC: bd/system/ip/system_axi_mem_interconnect_0/bd_0/ip/ip_31/bd_518a_swn_1_ooc.xdc

# XDC: bd/system/ip/system_axi_mem_interconnect_0/bd_0/ip/ip_32/bd_518a_sbn_1_ooc.xdc

# XDC: bd/system/ip/system_axi_mem_interconnect_0/bd_0/ip/ip_33/bd_518a_m00s2a_0_ooc.xdc

# XDC: bd/system/ip/system_axi_mem_interconnect_0/bd_0/ip/ip_34/bd_518a_m00arn_0_ooc.xdc

# XDC: bd/system/ip/system_axi_mem_interconnect_0/bd_0/ip/ip_35/bd_518a_m00rn_0_ooc.xdc

# XDC: bd/system/ip/system_axi_mem_interconnect_0/bd_0/ip/ip_36/bd_518a_m00awn_0_ooc.xdc

# XDC: bd/system/ip/system_axi_mem_interconnect_0/bd_0/ip/ip_37/bd_518a_m00wn_0_ooc.xdc

# XDC: bd/system/ip/system_axi_mem_interconnect_0/bd_0/ip/ip_38/bd_518a_m00bn_0_ooc.xdc

# XDC: bd/system/xilinx/common/up_clock_mon_constr.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_rx_axi_0 || ORIG_REF_NAME==system_rx_axi_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/system/ip/system_rx_axi_0/system_rx_axi_0_ooc.xdc

# XDC: bd/system/ip/system_rx_axi_0/axi_jesd204_rx_constr.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_rx_axi_0 || ORIG_REF_NAME==system_rx_axi_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/system/ip/system_rx_0/system_rx_0_constr.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_rx_0 || ORIG_REF_NAME==system_rx_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/system/xilinx/common/up_xfer_cntrl_constr.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_axi_ad9250_core_0 || ORIG_REF_NAME==system_axi_ad9250_core_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/system/xilinx/common/ad_rst_constr.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_axi_ad9250_core_0 || ORIG_REF_NAME==system_axi_ad9250_core_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/system/xilinx/common/up_xfer_status_constr.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_axi_ad9250_core_0 || ORIG_REF_NAME==system_axi_ad9250_core_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/system/xilinx/common/up_clock_mon_constr.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_axi_ad9250_core_0 || ORIG_REF_NAME==system_axi_ad9250_core_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/system/ip/system_util_fmcjesdadc1_xcvr_0/util_adxcvr_constr.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_util_fmcjesdadc1_xcvr_0 || ORIG_REF_NAME==system_util_fmcjesdadc1_xcvr_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/system/ip/system_ila_0_0/ila_v6_2/constraints/ila_impl.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_ila_0_0 || ORIG_REF_NAME==system_ila_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/system/ip/system_ila_0_0/ila_v6_2/constraints/ila.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_ila_0_0 || ORIG_REF_NAME==system_ila_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/system/ip/system_ila_0_0/system_ila_0_0_ooc.xdc

# XDC: bd/system/system_ooc.xdc
